//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Fuel
{
	private FuelType type
	{
		get;
		set;
	}

	private Double quantity
	{
		get;
		set;
	}

	public virtual FuelType FuelType
	{
		get;
		set;
	}

	public Fuel()
	{
	}

}

