//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class HorseDrawnCarriage : NonMotorizedVehicle
{
    public static int MAX_DISTANCE = 250;
    public HorseDrawnCarriage() {
        ID = 9;
    }
	private int horseNumber
	{
		get;
		set;
	}

}

