//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class MotorizedVehicle : Vehicle
{
	private int tankVolume
	{
		get;
		set;
	}
    private Double _consumption;

    public Double consumption { get { return _consumption; } set { _consumption = value; } }

	public Fuel Fuel
	{
		get;
		set;
	}

}

