//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class MotorizedVehicle : Vehicle
{
	private int tankVolume
	{
		get;
		set;
	}

	private Double consumption
	{
		get;
		set;
	}

	public virtual Fuel Fuel
	{
		get;
		set;
	}

}

