//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Vehicle
{
	private int maxDistance
	{
		get;
		set;
	}

	private int driverAge
	{
		get;
		set;
	}

	private int curSpeed
	{
		get;
		set;
	}

	private int maxSpeed
	{
		get;
		set;
	}

	private int weight
	{
		get;
		set;
	}

	private int color
	{
		get;
		set;
	}

	public virtual void info()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setSpeed(object Integer)
	{
		throw new System.NotImplementedException();
	}

	public Vehicle()
	{
	}

}

